### ISSUE TITLE
Local fallback breaks italics

### ISSUE THREAD

**Issue by RussellSprouts** [alfredxing/brick#41]
I have a site that uses EB Garamond, and on my machine italics do not work. I have EB Garamond installed locally. The local fallback for EB Garamond loads the "EB Garamond 12 Regular" font, so nothing is italicized.

``` css
@font-face{
    font-family:'Raleway';
    font-style:normal;
    font-weight:300;
    src:local('Raleway Light'),url(//brick.a.ssl.fastly.net/fonts/raleway/300.woff) format('woff')
}

@font-face{
    font-family:'Raleway';
    font-style:italic;
    font-weight:300;
    src:local('Raleway Light'),url(//brick.a.ssl.fastly.net/fonts/raleway/300i.woff) format('woff')
}

@font-face{
    font-family:'EB Garamond';
    font-style:normal;
    font-weight:400;
    src:local('EB Garamond 12 Regular'),url(//brick.a.ssl.fastly.net/fonts/ebgaramond/400.woff) format('woff')
}

@font-face{
    font-family:'EB Garamond';
    font-style:italic;
    font-weight:400;
    src:local('EB Garamond 12 Regular'),url(//brick.a.ssl.fastly.net/fonts/ebgaramond/400i.woff) format('woff')
}

@font-face{
    font-family:'EB Garamond';
    font-style:normal;
    font-weight:700;
    src:local(''),url(//brick.a.ssl.fastly.net/fonts/ebgaramond/700.woff) format('woff')
}

@font-face{
    font-family:'EB Garamond';
    font-style:italic;
    font-weight:700;
    src:local(''),url(//brick.a.ssl.fastly.net/fonts/ebgaramond/700i.woff) format('woff')
}
```
